version: 2
jobs:
  build:
    docker:
      - image: golang:1.19
    working_directory: /go/src/github.com/ijt/goparsify
    steps:
      - checkout
      - run: dep ensure --vendor-only
      - run: go vet ./...
      - run: go test -v ./...
